name: Go CI

on:
  workflow_dispatch:
  pull-request:
    branches:
      - main
    paths:
      - "go/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.1"

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./go

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run ./...
        working-directory: ./go

      - name: Run tests and generate coverage report
        run: go test -coverprofile=coverage.out ./...
        working-directory: ./go

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          file: coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: go build -v ./...
        working-directory: ./go

      - name: Install Nancy
        run: go install github.com/sonatype-nexus-community/nancy@latest

      - name: Run Nancy
        run: go list -json -deps ./... | nancy sleuth --loud
        working-directory: ./go

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...
        working-directory: ./go
